name: wisy_challenge
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  firebase_core: ^2.15.0
  camerawesome: ^1.4.0
  cloud_firestore: ^4.8.3
  firebase_storage: ^11.2.5
  flutter_riverpod: ^2.3.6
  path_provider: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0




flutter:


  uses-material-design: true

