// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARDjGx2CBhiepEQAwE9unddMymg_gmiak',
    appId: '1:956687503386:web:4ddf012a5574c20d3e41a3',
    messagingSenderId: '956687503386',
    projectId: 'wisylucasballestrino',
    authDomain: 'wisylucasballestrino.firebaseapp.com',
    storageBucket: 'wisylucasballestrino.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMRsNqTu10LxMiEE6lx5tu24mdMBK2tiU',
    appId: '1:956687503386:android:08fbd5b3b59d0efa3e41a3',
    messagingSenderId: '956687503386',
    projectId: 'wisylucasballestrino',
    storageBucket: 'wisylucasballestrino.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUqcsESKNnUEGeiVKWRfTJt74ImndDQtM',
    appId: '1:956687503386:ios:dec6dad25e6e227e3e41a3',
    messagingSenderId: '956687503386',
    projectId: 'wisylucasballestrino',
    storageBucket: 'wisylucasballestrino.appspot.com',
    iosClientId: '956687503386-d0gmr0skch9glajv7mrq0vl1lmb6uvtq.apps.googleusercontent.com',
    iosBundleId: 'com.example.wisyChallenge',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUqcsESKNnUEGeiVKWRfTJt74ImndDQtM',
    appId: '1:956687503386:ios:8e29854705b85ef33e41a3',
    messagingSenderId: '956687503386',
    projectId: 'wisylucasballestrino',
    storageBucket: 'wisylucasballestrino.appspot.com',
    iosClientId: '956687503386-63gtl0q0fdknhv5a362o0vie89d9n5o8.apps.googleusercontent.com',
    iosBundleId: 'com.example.wisyChallenge.RunnerTests',
  );
}
